// GENERATED by gen_webgpu_stubs.py - do not hand-edit.
// Mechanical "not yet implemented" stubs for the webgpu.h C ABI, so the Switch
// build links while the real deko3d-backed implementation is filled in
// incrementally. Calling any of these aborts with the function name, so a reached
// stub shows up immediately instead of misbehaving silently.
#include "webgpu_deko3d_stub_support.h"
#include <webgpu/webgpu.h>

extern "C" {

void wgpuGetInstanceFeatures(WGPUSupportedInstanceFeatures * features) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuGetInstanceFeatures");
}

WGPUStatus wgpuGetInstanceLimits(WGPUInstanceLimits * limits) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuGetInstanceLimits");
  return {};
}

WGPUBool wgpuHasInstanceFeature(WGPUInstanceFeatureName feature) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuHasInstanceFeature");
  return {};
}

WGPUProc wgpuGetProcAddress(WGPUStringView procName) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuGetProcAddress");
  return {};
}

WGPUDevice wgpuAdapterCreateDevice(WGPUAdapter adapter, WGPU_NULLABLE WGPUDeviceDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterCreateDevice");
  return {};
}

void wgpuAdapterGetFeatures(WGPUAdapter adapter, WGPUSupportedFeatures * features) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterGetFeatures");
}

WGPUStatus wgpuAdapterGetFormatCapabilities(WGPUAdapter adapter, WGPUTextureFormat format, WGPUDawnFormatCapabilities * capabilities) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterGetFormatCapabilities");
  return {};
}

WGPUStatus wgpuAdapterGetInfo(WGPUAdapter adapter, WGPUAdapterInfo * info) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterGetInfo");
  return {};
}

WGPUInstance wgpuAdapterGetInstance(WGPUAdapter adapter) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterGetInstance");
  return {};
}

WGPUStatus wgpuAdapterGetLimits(WGPUAdapter adapter, WGPULimits * limits) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterGetLimits");
  return {};
}

WGPUBool wgpuAdapterHasFeature(WGPUAdapter adapter, WGPUFeatureName feature) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterHasFeature");
  return {};
}

WGPUFuture wgpuAdapterRequestDevice(WGPUAdapter adapter, WGPU_NULLABLE WGPUDeviceDescriptor const * descriptor, WGPURequestDeviceCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterRequestDevice");
  return {};
}

void wgpuAdapterAddRef(WGPUAdapter adapter) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterAddRef");
}

void wgpuAdapterRelease(WGPUAdapter adapter) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterRelease");
}

void wgpuAdapterInfoFreeMembers(WGPUAdapterInfo adapterInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterInfoFreeMembers");
}

void wgpuAdapterPropertiesMemoryHeapsFreeMembers(WGPUAdapterPropertiesMemoryHeaps adapterPropertiesMemoryHeaps) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterPropertiesMemoryHeapsFreeMembers");
}

void wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers(WGPUAdapterPropertiesSubgroupMatrixConfigs adapterPropertiesSubgroupMatrixConfigs) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuAdapterPropertiesSubgroupMatrixConfigsFreeMembers");
}

void wgpuBindGroupSetLabel(WGPUBindGroup bindGroup, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBindGroupSetLabel");
}

void wgpuBindGroupAddRef(WGPUBindGroup bindGroup) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBindGroupAddRef");
}

void wgpuBindGroupRelease(WGPUBindGroup bindGroup) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBindGroupRelease");
}

void wgpuBindGroupLayoutSetLabel(WGPUBindGroupLayout bindGroupLayout, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBindGroupLayoutSetLabel");
}

void wgpuBindGroupLayoutAddRef(WGPUBindGroupLayout bindGroupLayout) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBindGroupLayoutAddRef");
}

void wgpuBindGroupLayoutRelease(WGPUBindGroupLayout bindGroupLayout) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBindGroupLayoutRelease");
}

WGPUTexelBufferView wgpuBufferCreateTexelView(WGPUBuffer buffer, WGPUTexelBufferViewDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferCreateTexelView");
  return {};
}

void wgpuBufferDestroy(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferDestroy");
}

void const * wgpuBufferGetConstMappedRange(WGPUBuffer buffer, size_t offset, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferGetConstMappedRange");
  return {};
}

void * wgpuBufferGetMappedRange(WGPUBuffer buffer, size_t offset, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferGetMappedRange");
  return {};
}

WGPUBufferMapState wgpuBufferGetMapState(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferGetMapState");
  return {};
}

uint64_t wgpuBufferGetSize(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferGetSize");
  return {};
}

WGPUBufferUsage wgpuBufferGetUsage(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferGetUsage");
  return {};
}

WGPUFuture wgpuBufferMapAsync(WGPUBuffer buffer, WGPUMapMode mode, size_t offset, size_t size, WGPUBufferMapCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferMapAsync");
  return {};
}

WGPUStatus wgpuBufferReadMappedRange(WGPUBuffer buffer, size_t offset, void * data, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferReadMappedRange");
  return {};
}

void wgpuBufferSetLabel(WGPUBuffer buffer, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferSetLabel");
}

void wgpuBufferUnmap(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferUnmap");
}

WGPUStatus wgpuBufferWriteMappedRange(WGPUBuffer buffer, size_t offset, void const * data, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferWriteMappedRange");
  return {};
}

void wgpuBufferAddRef(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferAddRef");
}

void wgpuBufferRelease(WGPUBuffer buffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuBufferRelease");
}

void wgpuCommandBufferSetLabel(WGPUCommandBuffer commandBuffer, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandBufferSetLabel");
}

void wgpuCommandBufferAddRef(WGPUCommandBuffer commandBuffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandBufferAddRef");
}

void wgpuCommandBufferRelease(WGPUCommandBuffer commandBuffer) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandBufferRelease");
}

WGPUComputePassEncoder wgpuCommandEncoderBeginComputePass(WGPUCommandEncoder commandEncoder, WGPU_NULLABLE WGPUComputePassDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderBeginComputePass");
  return {};
}

WGPURenderPassEncoder wgpuCommandEncoderBeginRenderPass(WGPUCommandEncoder commandEncoder, WGPURenderPassDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderBeginRenderPass");
  return {};
}

void wgpuCommandEncoderClearBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer buffer, uint64_t offset, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderClearBuffer");
}

void wgpuCommandEncoderCopyBufferToBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer source, uint64_t sourceOffset, WGPUBuffer destination, uint64_t destinationOffset, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderCopyBufferToBuffer");
}

void wgpuCommandEncoderCopyBufferToTexture(WGPUCommandEncoder commandEncoder, WGPUTexelCopyBufferInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderCopyBufferToTexture");
}

void wgpuCommandEncoderCopyTextureToBuffer(WGPUCommandEncoder commandEncoder, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyBufferInfo const * destination, WGPUExtent3D const * copySize) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderCopyTextureToBuffer");
}

void wgpuCommandEncoderCopyTextureToTexture(WGPUCommandEncoder commandEncoder, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderCopyTextureToTexture");
}

WGPUCommandBuffer wgpuCommandEncoderFinish(WGPUCommandEncoder commandEncoder, WGPU_NULLABLE WGPUCommandBufferDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderFinish");
  return {};
}

void wgpuCommandEncoderInjectValidationError(WGPUCommandEncoder commandEncoder, WGPUStringView message) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderInjectValidationError");
}

void wgpuCommandEncoderInsertDebugMarker(WGPUCommandEncoder commandEncoder, WGPUStringView markerLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderInsertDebugMarker");
}

void wgpuCommandEncoderPopDebugGroup(WGPUCommandEncoder commandEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderPopDebugGroup");
}

void wgpuCommandEncoderPushDebugGroup(WGPUCommandEncoder commandEncoder, WGPUStringView groupLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderPushDebugGroup");
}

void wgpuCommandEncoderResolveQuerySet(WGPUCommandEncoder commandEncoder, WGPUQuerySet querySet, uint32_t firstQuery, uint32_t queryCount, WGPUBuffer destination, uint64_t destinationOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderResolveQuerySet");
}

void wgpuCommandEncoderSetLabel(WGPUCommandEncoder commandEncoder, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderSetLabel");
}

void wgpuCommandEncoderWriteBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer buffer, uint64_t bufferOffset, uint8_t const * data, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderWriteBuffer");
}

void wgpuCommandEncoderWriteTimestamp(WGPUCommandEncoder commandEncoder, WGPUQuerySet querySet, uint32_t queryIndex) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderWriteTimestamp");
}

void wgpuCommandEncoderAddRef(WGPUCommandEncoder commandEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderAddRef");
}

void wgpuCommandEncoderRelease(WGPUCommandEncoder commandEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuCommandEncoderRelease");
}

void wgpuComputePassEncoderDispatchWorkgroups(WGPUComputePassEncoder computePassEncoder, uint32_t workgroupCountX, uint32_t workgroupCountY, uint32_t workgroupCountZ) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderDispatchWorkgroups");
}

void wgpuComputePassEncoderDispatchWorkgroupsIndirect(WGPUComputePassEncoder computePassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderDispatchWorkgroupsIndirect");
}

void wgpuComputePassEncoderEnd(WGPUComputePassEncoder computePassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderEnd");
}

void wgpuComputePassEncoderInsertDebugMarker(WGPUComputePassEncoder computePassEncoder, WGPUStringView markerLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderInsertDebugMarker");
}

void wgpuComputePassEncoderPopDebugGroup(WGPUComputePassEncoder computePassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderPopDebugGroup");
}

void wgpuComputePassEncoderPushDebugGroup(WGPUComputePassEncoder computePassEncoder, WGPUStringView groupLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderPushDebugGroup");
}

void wgpuComputePassEncoderSetBindGroup(WGPUComputePassEncoder computePassEncoder, uint32_t groupIndex, WGPU_NULLABLE WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderSetBindGroup");
}

void wgpuComputePassEncoderSetImmediates(WGPUComputePassEncoder computePassEncoder, uint32_t offset, void const * data, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderSetImmediates");
}

void wgpuComputePassEncoderSetLabel(WGPUComputePassEncoder computePassEncoder, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderSetLabel");
}

void wgpuComputePassEncoderSetPipeline(WGPUComputePassEncoder computePassEncoder, WGPUComputePipeline pipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderSetPipeline");
}

void wgpuComputePassEncoderSetResourceTable(WGPUComputePassEncoder computePassEncoder, WGPU_NULLABLE WGPUResourceTable table) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderSetResourceTable");
}

void wgpuComputePassEncoderWriteTimestamp(WGPUComputePassEncoder computePassEncoder, WGPUQuerySet querySet, uint32_t queryIndex) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderWriteTimestamp");
}

void wgpuComputePassEncoderAddRef(WGPUComputePassEncoder computePassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderAddRef");
}

void wgpuComputePassEncoderRelease(WGPUComputePassEncoder computePassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePassEncoderRelease");
}

WGPUBindGroupLayout wgpuComputePipelineGetBindGroupLayout(WGPUComputePipeline computePipeline, uint32_t groupIndex) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePipelineGetBindGroupLayout");
  return {};
}

void wgpuComputePipelineSetLabel(WGPUComputePipeline computePipeline, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePipelineSetLabel");
}

void wgpuComputePipelineAddRef(WGPUComputePipeline computePipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePipelineAddRef");
}

void wgpuComputePipelineRelease(WGPUComputePipeline computePipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuComputePipelineRelease");
}

void wgpuDawnDrmFormatCapabilitiesFreeMembers(WGPUDawnDrmFormatCapabilities dawnDrmFormatCapabilities) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDawnDrmFormatCapabilitiesFreeMembers");
}

WGPUBindGroup wgpuDeviceCreateBindGroup(WGPUDevice device, WGPUBindGroupDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateBindGroup");
  return {};
}

WGPUBindGroupLayout wgpuDeviceCreateBindGroupLayout(WGPUDevice device, WGPUBindGroupLayoutDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateBindGroupLayout");
  return {};
}

WGPU_NULLABLE WGPUBuffer wgpuDeviceCreateBuffer(WGPUDevice device, WGPUBufferDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateBuffer");
  return {};
}

WGPUCommandEncoder wgpuDeviceCreateCommandEncoder(WGPUDevice device, WGPU_NULLABLE WGPUCommandEncoderDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateCommandEncoder");
  return {};
}

WGPUComputePipeline wgpuDeviceCreateComputePipeline(WGPUDevice device, WGPUComputePipelineDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateComputePipeline");
  return {};
}

WGPUFuture wgpuDeviceCreateComputePipelineAsync(WGPUDevice device, WGPUComputePipelineDescriptor const * descriptor, WGPUCreateComputePipelineAsyncCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateComputePipelineAsync");
  return {};
}

WGPUBuffer wgpuDeviceCreateErrorBuffer(WGPUDevice device, WGPUBufferDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateErrorBuffer");
  return {};
}

WGPUExternalTexture wgpuDeviceCreateErrorExternalTexture(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateErrorExternalTexture");
  return {};
}

WGPUShaderModule wgpuDeviceCreateErrorShaderModule(WGPUDevice device, WGPUShaderModuleDescriptor const * descriptor, WGPUStringView errorMessage) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateErrorShaderModule");
  return {};
}

WGPUTexture wgpuDeviceCreateErrorTexture(WGPUDevice device, WGPUTextureDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateErrorTexture");
  return {};
}

WGPUExternalTexture wgpuDeviceCreateExternalTexture(WGPUDevice device, WGPUExternalTextureDescriptor const * externalTextureDescriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateExternalTexture");
  return {};
}

WGPUPipelineLayout wgpuDeviceCreatePipelineLayout(WGPUDevice device, WGPUPipelineLayoutDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreatePipelineLayout");
  return {};
}

WGPUQuerySet wgpuDeviceCreateQuerySet(WGPUDevice device, WGPUQuerySetDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateQuerySet");
  return {};
}

WGPURenderBundleEncoder wgpuDeviceCreateRenderBundleEncoder(WGPUDevice device, WGPURenderBundleEncoderDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateRenderBundleEncoder");
  return {};
}

WGPURenderPipeline wgpuDeviceCreateRenderPipeline(WGPUDevice device, WGPURenderPipelineDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateRenderPipeline");
  return {};
}

WGPUFuture wgpuDeviceCreateRenderPipelineAsync(WGPUDevice device, WGPURenderPipelineDescriptor const * descriptor, WGPUCreateRenderPipelineAsyncCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateRenderPipelineAsync");
  return {};
}

WGPUResourceTable wgpuDeviceCreateResourceTable(WGPUDevice device, WGPUResourceTableDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateResourceTable");
  return {};
}

WGPUSampler wgpuDeviceCreateSampler(WGPUDevice device, WGPU_NULLABLE WGPUSamplerDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateSampler");
  return {};
}

WGPUShaderModule wgpuDeviceCreateShaderModule(WGPUDevice device, WGPUShaderModuleDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateShaderModule");
  return {};
}

WGPUTexture wgpuDeviceCreateTexture(WGPUDevice device, WGPUTextureDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceCreateTexture");
  return {};
}

void wgpuDeviceDestroy(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceDestroy");
}

void wgpuDeviceForceLoss(WGPUDevice device, WGPUDeviceLostReason type, WGPUStringView message) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceForceLoss");
}

WGPUAdapter wgpuDeviceGetAdapter(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetAdapter");
  return {};
}

WGPUStatus wgpuDeviceGetAdapterInfo(WGPUDevice device, WGPUAdapterInfo * adapterInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetAdapterInfo");
  return {};
}

WGPUStatus wgpuDeviceGetAHardwareBufferProperties(WGPUDevice device, void * handle, WGPUAHardwareBufferProperties * properties) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetAHardwareBufferProperties");
  return {};
}

void wgpuDeviceGetFeatures(WGPUDevice device, WGPUSupportedFeatures * features) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetFeatures");
}

WGPUStatus wgpuDeviceGetLimits(WGPUDevice device, WGPULimits * limits) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetLimits");
  return {};
}

WGPUFuture wgpuDeviceGetLostFuture(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetLostFuture");
  return {};
}

WGPUQueue wgpuDeviceGetQueue(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceGetQueue");
  return {};
}

WGPUBool wgpuDeviceHasFeature(WGPUDevice device, WGPUFeatureName feature) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceHasFeature");
  return {};
}

WGPUSharedBufferMemory wgpuDeviceImportSharedBufferMemory(WGPUDevice device, WGPUSharedBufferMemoryDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceImportSharedBufferMemory");
  return {};
}

WGPUSharedFence wgpuDeviceImportSharedFence(WGPUDevice device, WGPUSharedFenceDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceImportSharedFence");
  return {};
}

WGPUSharedTextureMemory wgpuDeviceImportSharedTextureMemory(WGPUDevice device, WGPUSharedTextureMemoryDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceImportSharedTextureMemory");
  return {};
}

void wgpuDeviceInjectError(WGPUDevice device, WGPUErrorType type, WGPUStringView message) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceInjectError");
}

WGPUFuture wgpuDevicePopErrorScope(WGPUDevice device, WGPUPopErrorScopeCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDevicePopErrorScope");
  return {};
}

void wgpuDevicePushErrorScope(WGPUDevice device, WGPUErrorFilter filter) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDevicePushErrorScope");
}

void wgpuDeviceSetLabel(WGPUDevice device, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceSetLabel");
}

void wgpuDeviceSetLoggingCallback(WGPUDevice device, WGPULoggingCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceSetLoggingCallback");
}

void wgpuDeviceTick(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceTick");
}

void wgpuDeviceValidateTextureDescriptor(WGPUDevice device, WGPUTextureDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceValidateTextureDescriptor");
}

void wgpuDeviceAddRef(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceAddRef");
}

void wgpuDeviceRelease(WGPUDevice device) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuDeviceRelease");
}

void wgpuExternalTextureDestroy(WGPUExternalTexture externalTexture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuExternalTextureDestroy");
}

void wgpuExternalTextureExpire(WGPUExternalTexture externalTexture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuExternalTextureExpire");
}

void wgpuExternalTextureRefresh(WGPUExternalTexture externalTexture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuExternalTextureRefresh");
}

void wgpuExternalTextureSetLabel(WGPUExternalTexture externalTexture, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuExternalTextureSetLabel");
}

void wgpuExternalTextureAddRef(WGPUExternalTexture externalTexture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuExternalTextureAddRef");
}

void wgpuExternalTextureRelease(WGPUExternalTexture externalTexture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuExternalTextureRelease");
}

WGPUSurface wgpuInstanceCreateSurface(WGPUInstance instance, WGPUSurfaceDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuInstanceCreateSurface");
  return {};
}

void wgpuInstanceGetWGSLLanguageFeatures(WGPUInstance instance, WGPUSupportedWGSLLanguageFeatures * features) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuInstanceGetWGSLLanguageFeatures");
}

WGPUBool wgpuInstanceHasWGSLLanguageFeature(WGPUInstance instance, WGPUWGSLLanguageFeatureName feature) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuInstanceHasWGSLLanguageFeature");
  return {};
}

void wgpuInstanceProcessEvents(WGPUInstance instance) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuInstanceProcessEvents");
}

WGPUFuture wgpuInstanceRequestAdapter(WGPUInstance instance, WGPU_NULLABLE WGPURequestAdapterOptions const * options, WGPURequestAdapterCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuInstanceRequestAdapter");
  return {};
}

WGPUWaitStatus wgpuInstanceWaitAny(WGPUInstance instance, size_t futureCount, WGPU_NULLABLE WGPUFutureWaitInfo * futures, uint64_t timeoutNS) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuInstanceWaitAny");
  return {};
}

void wgpuPipelineLayoutSetLabel(WGPUPipelineLayout pipelineLayout, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuPipelineLayoutSetLabel");
}

void wgpuPipelineLayoutAddRef(WGPUPipelineLayout pipelineLayout) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuPipelineLayoutAddRef");
}

void wgpuPipelineLayoutRelease(WGPUPipelineLayout pipelineLayout) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuPipelineLayoutRelease");
}

void wgpuQuerySetDestroy(WGPUQuerySet querySet) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQuerySetDestroy");
}

uint32_t wgpuQuerySetGetCount(WGPUQuerySet querySet) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQuerySetGetCount");
  return {};
}

WGPUQueryType wgpuQuerySetGetType(WGPUQuerySet querySet) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQuerySetGetType");
  return {};
}

void wgpuQuerySetSetLabel(WGPUQuerySet querySet, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQuerySetSetLabel");
}

void wgpuQuerySetAddRef(WGPUQuerySet querySet) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQuerySetAddRef");
}

void wgpuQuerySetRelease(WGPUQuerySet querySet) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQuerySetRelease");
}

void wgpuQueueCopyExternalTextureForBrowser(WGPUQueue queue, WGPUImageCopyExternalTexture const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize, WGPUCopyTextureForBrowserOptions const * options) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueCopyExternalTextureForBrowser");
}

void wgpuQueueCopyTextureForBrowser(WGPUQueue queue, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize, WGPUCopyTextureForBrowserOptions const * options) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueCopyTextureForBrowser");
}

WGPUFuture wgpuQueueOnSubmittedWorkDone(WGPUQueue queue, WGPUQueueWorkDoneCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueOnSubmittedWorkDone");
  return {};
}

void wgpuQueueSetLabel(WGPUQueue queue, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueSetLabel");
}

void wgpuQueueSubmit(WGPUQueue queue, size_t commandCount, WGPUCommandBuffer const * commands) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueSubmit");
}

void wgpuQueueWriteBuffer(WGPUQueue queue, WGPUBuffer buffer, uint64_t bufferOffset, void const * data, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueWriteBuffer");
}

void wgpuQueueWriteTexture(WGPUQueue queue, WGPUTexelCopyTextureInfo const * destination, void const * data, size_t dataSize, WGPUTexelCopyBufferLayout const * dataLayout, WGPUExtent3D const * writeSize) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueWriteTexture");
}

void wgpuQueueAddRef(WGPUQueue queue) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueAddRef");
}

void wgpuQueueRelease(WGPUQueue queue) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuQueueRelease");
}

void wgpuRenderBundleSetLabel(WGPURenderBundle renderBundle, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleSetLabel");
}

void wgpuRenderBundleAddRef(WGPURenderBundle renderBundle) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleAddRef");
}

void wgpuRenderBundleRelease(WGPURenderBundle renderBundle) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleRelease");
}

void wgpuRenderBundleEncoderDraw(WGPURenderBundleEncoder renderBundleEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderDraw");
}

void wgpuRenderBundleEncoderDrawIndexed(WGPURenderBundleEncoder renderBundleEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderDrawIndexed");
}

void wgpuRenderBundleEncoderDrawIndexedIndirect(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderDrawIndexedIndirect");
}

void wgpuRenderBundleEncoderDrawIndirect(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderDrawIndirect");
}

WGPURenderBundle wgpuRenderBundleEncoderFinish(WGPURenderBundleEncoder renderBundleEncoder, WGPU_NULLABLE WGPURenderBundleDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderFinish");
  return {};
}

void wgpuRenderBundleEncoderInsertDebugMarker(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView markerLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderInsertDebugMarker");
}

void wgpuRenderBundleEncoderPopDebugGroup(WGPURenderBundleEncoder renderBundleEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderPopDebugGroup");
}

void wgpuRenderBundleEncoderPushDebugGroup(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView groupLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderPushDebugGroup");
}

void wgpuRenderBundleEncoderSetBindGroup(WGPURenderBundleEncoder renderBundleEncoder, uint32_t groupIndex, WGPU_NULLABLE WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetBindGroup");
}

void wgpuRenderBundleEncoderSetImmediates(WGPURenderBundleEncoder renderBundleEncoder, uint32_t offset, void const * data, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetImmediates");
}

void wgpuRenderBundleEncoderSetIndexBuffer(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer buffer, WGPUIndexFormat format, uint64_t offset, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetIndexBuffer");
}

void wgpuRenderBundleEncoderSetLabel(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetLabel");
}

void wgpuRenderBundleEncoderSetPipeline(WGPURenderBundleEncoder renderBundleEncoder, WGPURenderPipeline pipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetPipeline");
}

void wgpuRenderBundleEncoderSetResourceTable(WGPURenderBundleEncoder renderBundleEncoder, WGPU_NULLABLE WGPUResourceTable table) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetResourceTable");
}

void wgpuRenderBundleEncoderSetVertexBuffer(WGPURenderBundleEncoder renderBundleEncoder, uint32_t slot, WGPU_NULLABLE WGPUBuffer buffer, uint64_t offset, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderSetVertexBuffer");
}

void wgpuRenderBundleEncoderAddRef(WGPURenderBundleEncoder renderBundleEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderAddRef");
}

void wgpuRenderBundleEncoderRelease(WGPURenderBundleEncoder renderBundleEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderBundleEncoderRelease");
}

void wgpuRenderPassEncoderBeginOcclusionQuery(WGPURenderPassEncoder renderPassEncoder, uint32_t queryIndex) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderBeginOcclusionQuery");
}

void wgpuRenderPassEncoderDraw(WGPURenderPassEncoder renderPassEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderDraw");
}

void wgpuRenderPassEncoderDrawIndexed(WGPURenderPassEncoder renderPassEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderDrawIndexed");
}

void wgpuRenderPassEncoderDrawIndexedIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderDrawIndexedIndirect");
}

void wgpuRenderPassEncoderDrawIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderDrawIndirect");
}

void wgpuRenderPassEncoderEnd(WGPURenderPassEncoder renderPassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderEnd");
}

void wgpuRenderPassEncoderEndOcclusionQuery(WGPURenderPassEncoder renderPassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderEndOcclusionQuery");
}

void wgpuRenderPassEncoderExecuteBundles(WGPURenderPassEncoder renderPassEncoder, size_t bundleCount, WGPURenderBundle const * bundles) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderExecuteBundles");
}

void wgpuRenderPassEncoderInsertDebugMarker(WGPURenderPassEncoder renderPassEncoder, WGPUStringView markerLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderInsertDebugMarker");
}

void wgpuRenderPassEncoderMultiDrawIndexedIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset, uint32_t maxDrawCount, WGPU_NULLABLE WGPUBuffer drawCountBuffer, uint64_t drawCountBufferOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderMultiDrawIndexedIndirect");
}

void wgpuRenderPassEncoderMultiDrawIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset, uint32_t maxDrawCount, WGPU_NULLABLE WGPUBuffer drawCountBuffer, uint64_t drawCountBufferOffset) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderMultiDrawIndirect");
}

void wgpuRenderPassEncoderPixelLocalStorageBarrier(WGPURenderPassEncoder renderPassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderPixelLocalStorageBarrier");
}

void wgpuRenderPassEncoderPopDebugGroup(WGPURenderPassEncoder renderPassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderPopDebugGroup");
}

void wgpuRenderPassEncoderPushDebugGroup(WGPURenderPassEncoder renderPassEncoder, WGPUStringView groupLabel) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderPushDebugGroup");
}

void wgpuRenderPassEncoderSetBindGroup(WGPURenderPassEncoder renderPassEncoder, uint32_t groupIndex, WGPU_NULLABLE WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetBindGroup");
}

void wgpuRenderPassEncoderSetBlendConstant(WGPURenderPassEncoder renderPassEncoder, WGPUColor const * color) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetBlendConstant");
}

void wgpuRenderPassEncoderSetImmediates(WGPURenderPassEncoder renderPassEncoder, uint32_t offset, void const * data, size_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetImmediates");
}

void wgpuRenderPassEncoderSetIndexBuffer(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer buffer, WGPUIndexFormat format, uint64_t offset, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetIndexBuffer");
}

void wgpuRenderPassEncoderSetLabel(WGPURenderPassEncoder renderPassEncoder, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetLabel");
}

void wgpuRenderPassEncoderSetPipeline(WGPURenderPassEncoder renderPassEncoder, WGPURenderPipeline pipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetPipeline");
}

void wgpuRenderPassEncoderSetResourceTable(WGPURenderPassEncoder renderPassEncoder, WGPU_NULLABLE WGPUResourceTable table) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetResourceTable");
}

void wgpuRenderPassEncoderSetScissorRect(WGPURenderPassEncoder renderPassEncoder, uint32_t x, uint32_t y, uint32_t width, uint32_t height) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetScissorRect");
}

void wgpuRenderPassEncoderSetStencilReference(WGPURenderPassEncoder renderPassEncoder, uint32_t reference) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetStencilReference");
}

void wgpuRenderPassEncoderSetVertexBuffer(WGPURenderPassEncoder renderPassEncoder, uint32_t slot, WGPU_NULLABLE WGPUBuffer buffer, uint64_t offset, uint64_t size) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetVertexBuffer");
}

void wgpuRenderPassEncoderSetViewport(WGPURenderPassEncoder renderPassEncoder, float x, float y, float width, float height, float minDepth, float maxDepth) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderSetViewport");
}

void wgpuRenderPassEncoderWriteTimestamp(WGPURenderPassEncoder renderPassEncoder, WGPUQuerySet querySet, uint32_t queryIndex) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderWriteTimestamp");
}

void wgpuRenderPassEncoderAddRef(WGPURenderPassEncoder renderPassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderAddRef");
}

void wgpuRenderPassEncoderRelease(WGPURenderPassEncoder renderPassEncoder) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPassEncoderRelease");
}

WGPUBindGroupLayout wgpuRenderPipelineGetBindGroupLayout(WGPURenderPipeline renderPipeline, uint32_t groupIndex) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPipelineGetBindGroupLayout");
  return {};
}

void wgpuRenderPipelineSetLabel(WGPURenderPipeline renderPipeline, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPipelineSetLabel");
}

void wgpuRenderPipelineAddRef(WGPURenderPipeline renderPipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPipelineAddRef");
}

void wgpuRenderPipelineRelease(WGPURenderPipeline renderPipeline) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuRenderPipelineRelease");
}

void wgpuResourceTableDestroy(WGPUResourceTable resourceTable) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableDestroy");
}

uint32_t wgpuResourceTableGetSize(WGPUResourceTable resourceTable) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableGetSize");
  return {};
}

uint32_t wgpuResourceTableInsertBinding(WGPUResourceTable resourceTable, WGPUBindingResource const * resource) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableInsertBinding");
  return {};
}

WGPUStatus wgpuResourceTableRemoveBinding(WGPUResourceTable resourceTable, uint32_t slot) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableRemoveBinding");
  return {};
}

void wgpuResourceTableSetLabel(WGPUResourceTable resourceTable, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableSetLabel");
}

WGPUStatus wgpuResourceTableUpdate(WGPUResourceTable resourceTable, uint32_t slot, WGPUBindingResource const * resource) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableUpdate");
  return {};
}

void wgpuResourceTableAddRef(WGPUResourceTable resourceTable) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableAddRef");
}

void wgpuResourceTableRelease(WGPUResourceTable resourceTable) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuResourceTableRelease");
}

void wgpuSamplerSetLabel(WGPUSampler sampler, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSamplerSetLabel");
}

void wgpuSamplerAddRef(WGPUSampler sampler) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSamplerAddRef");
}

void wgpuSamplerRelease(WGPUSampler sampler) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSamplerRelease");
}

WGPUFuture wgpuShaderModuleGetCompilationInfo(WGPUShaderModule shaderModule, WGPUCompilationInfoCallbackInfo callbackInfo) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuShaderModuleGetCompilationInfo");
  return {};
}

void wgpuShaderModuleSetLabel(WGPUShaderModule shaderModule, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuShaderModuleSetLabel");
}

void wgpuShaderModuleAddRef(WGPUShaderModule shaderModule) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuShaderModuleAddRef");
}

void wgpuShaderModuleRelease(WGPUShaderModule shaderModule) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuShaderModuleRelease");
}

WGPUStatus wgpuSharedBufferMemoryBeginAccess(WGPUSharedBufferMemory sharedBufferMemory, WGPUBuffer buffer, WGPUSharedBufferMemoryBeginAccessDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryBeginAccess");
  return {};
}

WGPUBuffer wgpuSharedBufferMemoryCreateBuffer(WGPUSharedBufferMemory sharedBufferMemory, WGPU_NULLABLE WGPUBufferDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryCreateBuffer");
  return {};
}

WGPUStatus wgpuSharedBufferMemoryEndAccess(WGPUSharedBufferMemory sharedBufferMemory, WGPUBuffer buffer, WGPUSharedBufferMemoryEndAccessState * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryEndAccess");
  return {};
}

WGPUStatus wgpuSharedBufferMemoryGetProperties(WGPUSharedBufferMemory sharedBufferMemory, WGPUSharedBufferMemoryProperties * properties) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryGetProperties");
  return {};
}

WGPUBool wgpuSharedBufferMemoryIsDeviceLost(WGPUSharedBufferMemory sharedBufferMemory) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryIsDeviceLost");
  return {};
}

void wgpuSharedBufferMemorySetLabel(WGPUSharedBufferMemory sharedBufferMemory, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemorySetLabel");
}

void wgpuSharedBufferMemoryAddRef(WGPUSharedBufferMemory sharedBufferMemory) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryAddRef");
}

void wgpuSharedBufferMemoryRelease(WGPUSharedBufferMemory sharedBufferMemory) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryRelease");
}

void wgpuSharedBufferMemoryEndAccessStateFreeMembers(WGPUSharedBufferMemoryEndAccessState sharedBufferMemoryEndAccessState) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedBufferMemoryEndAccessStateFreeMembers");
}

void wgpuSharedFenceExportInfo(WGPUSharedFence sharedFence, WGPUSharedFenceExportInfo * info) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedFenceExportInfo");
}

void wgpuSharedFenceSetLabel(WGPUSharedFence sharedFence, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedFenceSetLabel");
}

void wgpuSharedFenceAddRef(WGPUSharedFence sharedFence) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedFenceAddRef");
}

void wgpuSharedFenceRelease(WGPUSharedFence sharedFence) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedFenceRelease");
}

WGPUStatus wgpuSharedTextureMemoryBeginAccess(WGPUSharedTextureMemory sharedTextureMemory, WGPUTexture texture, WGPUSharedTextureMemoryBeginAccessDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryBeginAccess");
  return {};
}

WGPUTexture wgpuSharedTextureMemoryCreateTexture(WGPUSharedTextureMemory sharedTextureMemory, WGPU_NULLABLE WGPUTextureDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryCreateTexture");
  return {};
}

WGPUStatus wgpuSharedTextureMemoryEndAccess(WGPUSharedTextureMemory sharedTextureMemory, WGPUTexture texture, WGPUSharedTextureMemoryEndAccessState * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryEndAccess");
  return {};
}

WGPUStatus wgpuSharedTextureMemoryGetProperties(WGPUSharedTextureMemory sharedTextureMemory, WGPUSharedTextureMemoryProperties * properties) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryGetProperties");
  return {};
}

WGPUBool wgpuSharedTextureMemoryIsDeviceLost(WGPUSharedTextureMemory sharedTextureMemory) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryIsDeviceLost");
  return {};
}

void wgpuSharedTextureMemorySetLabel(WGPUSharedTextureMemory sharedTextureMemory, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemorySetLabel");
}

void wgpuSharedTextureMemoryAddRef(WGPUSharedTextureMemory sharedTextureMemory) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryAddRef");
}

void wgpuSharedTextureMemoryRelease(WGPUSharedTextureMemory sharedTextureMemory) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryRelease");
}

void wgpuSharedTextureMemoryEndAccessStateFreeMembers(WGPUSharedTextureMemoryEndAccessState sharedTextureMemoryEndAccessState) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSharedTextureMemoryEndAccessStateFreeMembers");
}

void wgpuSupportedFeaturesFreeMembers(WGPUSupportedFeatures supportedFeatures) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSupportedFeaturesFreeMembers");
}

void wgpuSupportedInstanceFeaturesFreeMembers(WGPUSupportedInstanceFeatures supportedInstanceFeatures) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSupportedInstanceFeaturesFreeMembers");
}

void wgpuSupportedWGSLLanguageFeaturesFreeMembers(WGPUSupportedWGSLLanguageFeatures supportedWGSLLanguageFeatures) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSupportedWGSLLanguageFeaturesFreeMembers");
}

void wgpuSurfaceConfigure(WGPUSurface surface, WGPUSurfaceConfiguration const * config) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceConfigure");
}

WGPUStatus wgpuSurfaceGetCapabilities(WGPUSurface surface, WGPUAdapter adapter, WGPUSurfaceCapabilities * capabilities) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceGetCapabilities");
  return {};
}

void wgpuSurfaceGetCurrentTexture(WGPUSurface surface, WGPUSurfaceTexture * surfaceTexture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceGetCurrentTexture");
}

WGPUStatus wgpuSurfacePresent(WGPUSurface surface) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfacePresent");
  return {};
}

void wgpuSurfaceSetLabel(WGPUSurface surface, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceSetLabel");
}

void wgpuSurfaceUnconfigure(WGPUSurface surface) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceUnconfigure");
}

void wgpuSurfaceAddRef(WGPUSurface surface) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceAddRef");
}

void wgpuSurfaceRelease(WGPUSurface surface) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceRelease");
}

void wgpuSurfaceCapabilitiesFreeMembers(WGPUSurfaceCapabilities surfaceCapabilities) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuSurfaceCapabilitiesFreeMembers");
}

void wgpuTexelBufferViewSetLabel(WGPUTexelBufferView texelBufferView, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTexelBufferViewSetLabel");
}

void wgpuTexelBufferViewAddRef(WGPUTexelBufferView texelBufferView) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTexelBufferViewAddRef");
}

void wgpuTexelBufferViewRelease(WGPUTexelBufferView texelBufferView) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTexelBufferViewRelease");
}

WGPUTextureView wgpuTextureCreateErrorView(WGPUTexture texture, WGPU_NULLABLE WGPUTextureViewDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureCreateErrorView");
  return {};
}

WGPUTextureView wgpuTextureCreateView(WGPUTexture texture, WGPU_NULLABLE WGPUTextureViewDescriptor const * descriptor) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureCreateView");
  return {};
}

void wgpuTextureDestroy(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureDestroy");
}

uint32_t wgpuTextureGetDepthOrArrayLayers(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetDepthOrArrayLayers");
  return {};
}

WGPUTextureDimension wgpuTextureGetDimension(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetDimension");
  return {};
}

WGPUTextureFormat wgpuTextureGetFormat(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetFormat");
  return {};
}

uint32_t wgpuTextureGetHeight(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetHeight");
  return {};
}

uint32_t wgpuTextureGetMipLevelCount(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetMipLevelCount");
  return {};
}

uint32_t wgpuTextureGetSampleCount(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetSampleCount");
  return {};
}

WGPUTextureViewDimension wgpuTextureGetTextureBindingViewDimension(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetTextureBindingViewDimension");
  return {};
}

WGPUTextureUsage wgpuTextureGetUsage(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetUsage");
  return {};
}

uint32_t wgpuTextureGetWidth(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureGetWidth");
  return {};
}

void wgpuTexturePin(WGPUTexture texture, WGPUTextureUsage usage) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTexturePin");
}

void wgpuTextureSetLabel(WGPUTexture texture, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureSetLabel");
}

void wgpuTextureSetOwnershipForMemoryDump(WGPUTexture texture, uint64_t ownerGuid) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureSetOwnershipForMemoryDump");
}

void wgpuTextureUnpin(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureUnpin");
}

void wgpuTextureAddRef(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureAddRef");
}

void wgpuTextureRelease(WGPUTexture texture) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureRelease");
}

void wgpuTextureViewSetLabel(WGPUTextureView textureView, WGPUStringView label) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureViewSetLabel");
}

void wgpuTextureViewAddRef(WGPUTextureView textureView) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureViewAddRef");
}

void wgpuTextureViewRelease(WGPUTextureView textureView) {
  aurora::deko3d::webgpu_stub_unimplemented("wgpuTextureViewRelease");
}

} // extern "C"
